### ISSUE TITLE
modelDescription.xml content

### ISSUE THREAD

**Issue by markaren** [robbr48/fmi4c#32]
Hi, I was contemplating replacing FMI Library with this one. However, I can't seem to find public functions to retreive data from the modelDescription.xml. Is this correct?

Also, for the start values, there seems no way of checking if one exists (a defult value is always retured).

Thanks!

**Comment by robbr48** [comment]
Hi,
There may be some API functions missing, but most data from modelDescription.xml should be available. You can for example call `fmiX_getNumberOfEventIndicators` to access the number of event indicators, which is read from the XML. Is there some data in particular that is not accessible?

The start values could be extended with a "startValuesExist" function. It should be quite easy, as the XML parse function already returns false if the attribute is not found. We just need to read the return value and make it accessible. I will add a separate issue forthis.

**Comment by markaren** [comment]
Indeed some of the information is available. I was really supposed to query about the meta data part of the XML. `modelName`, `modelIdentifier`, `author` etc. I see these are stored in `fmi4c_private.h`, but not publically accessable.

**Comment by robbr48** [comment]
I see, it looks like they are available for FMI2 and FMI3, ut not for FMI1. That should be quite easy to fix. I will have a look at it.

**Comment by markaren** [comment]
I have done some work in a fork to get this tool working with ecos https://github.com/Ecos-platform/ecos/tree/fmi4c

(1) FMI1 xml data
(2) Make it compatiable with CMake FetchContent

Would you like me to make a PR on the XML data as a beginning?
