### ISSUE TITLE
Memory not freed for `target` in `parseStringAttributeEzXml` function

### ISSUE THREAD

**Issue by lochel** [robbr48/fmi4c#63]
### Issue Description

The function `parseStringAttributeEzXml` allocates memory for the `target` pointer using `_strdup`. I cannot see that this get freed anywhere.

### Code in Question

```c
bool parseStringAttributeEzXml(ezxml_t element, const char *attributeName, const char **target)
{
    if(ezxml_attr(element, attributeName)) {
        (*target) = _strdup(ezxml_attr(element, attributeName));
        return true;
    }
    return false;
}
```

**Comment by robbr48** [comment]
Actually this is why we call `freeDuplicatedConstChar` for each one of the strings in `fmi4c_freeFmu`. It is a little annoying that it must be hard coded though. Perhaps each allocated string could be appended to an array, and then loop through this array at the end and free each element? That would be sort of a poor mans garbage collector.

**Comment by lochel** [comment]
I think is is now fixed. Thanks @robbr48.
